language: ruby
script: bundle exec rspec
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/rails-3.0.x.gemfile
  - gemfiles/rails-3.2.x.gemfile
  - gemfiles/rails-head.gemfile
  - Gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails-head.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails-3.0.x.gemfile
